bug fixes, missing primitives. Fixed bugs in the graph-readback implementation. It was reading back expression that were far too big,   due to scoping, sharing, ordering issues. Added enough missing primitives for the fe-in-fe evaluator to now be full graph-reducible. Fixed a Ferrum pretty-printing issue that was duplicating parts of the  list if the tail was non-nil.

diff --git a/cmds/runtest b/cmds/runtest
--- a/cmds/runtest
+++ b/cmds/runtest
@@ -1,4 +1,9 @@
 #!/usr/bin/env bash
+set -u # An unset variable is an error.
+set -e # Exit on first error.
+set -o pipefail # A pipeline fails if any command in the pipeline fails.
+# set -x # Display every command.
+trap "echo $'\x7'" EXIT # Go beep at the end.
 
 ulimit -s unlimited
 
@@ -21,10 +26,7 @@ node \
     --max-heap-size=16000 \
     "$ferrumDir"/ts/gen/cmds/runtest-nodejs.js "$@"
 
-exitCode=$?
-echo "EXIT CODE" $exitCode 
 
-# Go beep at the end
-echo $'\x7'
-
-exit $exitCode
+# exitCode=$?
+# echo "EXIT CODE" $exitCode 
+# exit $exitCode
